# Details of a user
---
configs:
  - name: Application1
    code: Application1
    id: 1
    configs:
      -  name: Application1 Service1
         envs:
           dev: http://18.191.233.254:8085/config-utils/abc.txt
           test: http://18.191.233.254:8085/config-utils/abc2.txt
           stage: http://18.191.233.254:8085/config-utils/abc3.txt
      -  name: Application1 Service2
         envs:
           dev: http://18.191.233.254:8085/config-utils/abc2.txt
  - name: Application2
    code: Application2
    id: 2
    configs:
      -  name: Application2 Services
         envs:
           dev: http://18.191.233.254:8085/config-utils/abc3.txt
           
