# Details of a user
---
configs:
  - name: Application1
    code: Application1
    id: 1
    configs:
      -  name: Application1 Service1
         envs:
           dev: http://localhost:8085/utility/abc.txt
           test: http://localhost:8085/utility/abc2.txt
           stage: http://localhost:8085/utility/abc3.txt
      -  name: Application1 Service2
         envs:
           dev: http://localhost:8085/utility/abc2.txt
  - name: Application2
    code: Application2
    id: 2
    configs:
      -  name: Application2 Services
         envs:
           dev: http://localhost:8085/utility/abc3.txt
           
